@contentType = application/json
//https://eminentitco.sharepoint.com/Sandbox/_api/web/lists/getbytitle('wkfl')/items?$skiptoken=Paged%3DTRUE%26p_ID%3D0&$top=5000&$select=GUID,ID,Title,DateOfDecision,ContentType,Attachments,AttachmentFiles,DocumentClearance/Id,DocumentClearance/Title,RoleType/Id,RoleType/RoleType,Role/Id,Role/EMail,Role/FirstName,Role/LastName,Role/WorkPhone,Role/Office,Role/Department,Role/JobTitle,Role/Title,Role/SipAddress,Role/Name,Status/Id,Status/Status&$expand=AttachmentFiles,DocumentClearance,RoleType,Role,Status&$orderBy=Attachments%20asc&$filter=DocumentClearance%20eq%202
//https://eminentitco.sharepoint.com/Sandbox/_api/web/lists/getbytitle('work')/items?$skiptoken=Paged%3DTRUE%26p_ID%3D0&$top=5000&$select=GUID,ID,Modified,Title,DateOfDecision,zSequence,zActive,ContentType,Attachments,AttachmentFiles,Editor/Title,DocumentClearance/Id,DocumentClearance/Title,RoleType/Id,RoleType/RoleType,Status/Id,Status/Status&$expand=AttachmentFiles,Editor,DocumentClearance,RoleType,Status&$orderBy=Attachments%20asc&draw=1&start=0&length=50&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1587674557622
# Get https://eminentitco.sharepoint.com/Sandbox/_api/web/lists/getbytitle('documentclearancework')/items
# ?$skiptoken=Paged%3DTRUE%26p_ID%3D0&$top=5000
# &$select=GUID,ID,Modified,FileLeafRef,Title,CurrentPerson,CurrentStatus,ContentType,Source/Id,Source/Source,Marking/Id,Marking/Marking
# &$expand=Source,Marking
# &$filter=(FSObjType%20eq%200)&$orderBy=FileLeafRef%20asc
# Content-Type: {{contentType}}
# accept: application/json

# Get https://eminentitco.sharepoint.com/Sandbox/_api/web/lists/getbytitle('documentclearancework')/items
# ?$skiptoken=Paged%3DTRUE%26p_ID%3D0&$top=5000
# &$select=GUID,ID,Modified,Source/Id,Source/Source
# &$expand=Source
# &$filter=(FSObjType%20eq%200)&$orderBy=FileLeafRef%20asc
# Content-Type: {{contentType}}
# accept: application/json;


# Get https://eminentitco.sharepoint.com/Sandbox/_api/Web/GetFileByServerRelativePath(decodedurl='/Sandbox/DocumentClearance/office%20-%20wwwwy%20-%20Copy.pdf')/ListItemAllFields
# Content-Type: {{contentType}}
# accept: application/json;

# Get https://eminentitco.sharepoint.com/Sandbox/_api/Web/Lists(guid'bd8e54e9-c648-42ec-92e2-1613598132d9')/Items(14)
# ?$select=GUID,ID,Modified,FileLeafRef,Title,CurrentPerson,CurrentStatus,ContentType,EncodedAbsUrl,Editor/Title,Priority/Id,Priority/Priority,Source/Id,Source/Source,Marking/Id,Marking/Marking
# &$expand=Editor,Priority,Source,Marking
# Content-Type: {{contentType}}
# accept: application/json;

Get https://eminentitco.sharepoint.com/Sandbox/DocumentClearance/Attachment%202%20-%20Proposal%20Form.docx
Content-Type: {{contentType}}
accept: application/json;