@contentType = application/json
https://eminentitco.sharepoint.com/Sandbox/_api/web/lists/getbytitle('wkfl')/items?$skiptoken=Paged%3DTRUE%26p_ID%3D0&$top=5000&$select=GUID,ID,Title,DateOfDecision,ContentType,Attachments,AttachmentFiles,DCMain/Id,DCMain/Title,RoleType/Id,RoleType/RoleType,Role/Id,Role/EMail,Role/FirstName,Role/LastName,Role/WorkPhone,Role/Office,Role/Department,Role/JobTitle,Role/Title,Role/SipAddress,Role/Name,Status/Id,Status/Status&$expand=AttachmentFiles,DCMain,RoleType,Role,Status&$orderBy=Attachments%20asc&$filter=DCMain%20eq%202
Content-Type: {{contentType}}
accept: application/json